name: macos-10.15
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-10.15]
        #python-version: [ 3.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
            brew install cmake ccache conan python3 libiconv

      - name: install conan
        run: |
          conan user
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add cyberduckninja https://api.bintray.com/conan/cyberduckninja/conan

      - name: build
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON
          cmake --build . --parallel 2

      - name: install dependons test
        run: pip install -r requirements.txt

      - name: install kernel
        run: jupyter kernelspec install --user kernels/ipython

      - name: run test
        run: ctest #pytest core/rocketjoe/python_sandbox/test_python_kernel.py
